version: "3.9"
services:
  mysql81:
    container_name: mysql81
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mario639  #estos environment los consigues en la pagina de docker hub para estas imagenes de base de datos de docker
      MYSQL_DATABASE: usuariosdb
    volumes:
      - data-mysql1:/var/lib/mysql1
    restart: always
    networks:
      - spring
  mysql82:
    container_name: mysql82
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mario639  #estos environment los consigues en la pagina de docker hub para estas imagenes de base de datos de docker
      MYSQL_DATABASE: cursosdb
    volumes:
      - data-mysql2:/var/lib/mysql2
    restart: always
    networks:
      - spring
  msvc-usuarios:
    container_name: msvc-usuarios
    build:
      context: .
      dockerfile: docker/Usuarios.Dockerfile
    ports:
      - "8080:8080"
    env_file: microservicio_usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql81
    restart: always
  msvc-cursos:
    container_name: msvc-cursos
    build:
      context: .
      dockerfile: docker/Cursos.Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - microservicio_cursos/.env
    networks:
      - spring
    depends_on:
      - mysql82
      - msvc-usuarios
    restart: always
volumes:
  data-mysql1:
    name: data-mysql1
  data-mysql2:
    name: data-mysql2
networks:
  spring:
    name: spring