apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
        - name: cursos
          image: bolters/cursos:latest
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              valueFrom: #tambien si no tiene configMap y solo quieres poner una variable de ambiente directo pones value: <valor deseado> y listo
                configMapKeyRef: #o tambien puedo poner variables de ambiente donde el valor lo busco en cualquier otro archivo yaml de kubernetes, ejemplo en la respectiva carpeta del curso
                  name: msvc-cursos
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: db_host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: db_pass
            - name: REST_TEMPLATE_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: rest_template_host
            - name: PROFILE
              value: dev