apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql82
spec:
  replicas: 1
  selector:
    matchLabels:
      role: mysql82
  template:
    metadata:
      labels:
        role: mysql82
    spec:
      containers:
        - name: mysql82
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mario639
            - name: MYSQL_DATABASE
              value: cursosdb
          volumeMounts:
            - name: data-mysql82
              mountPath: /var/lib/mysql82
      volumes:
        - name: data-mysql82
          hostPath:
            path: /var/lib/mysql82
            type: DirectoryOrCreate