apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  db_user: cm9vdA==
  db_pass: bWFyaW82Mzk=

---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  db_user: cm9vdA==
  db_pass: bWFyaW82Mzk=