apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  db_user: cm9vdA==
  db_pass: c2FzYQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  db_user: cG9zdGdyZXM=
  db_pass: c2FzYQ==